### ISSUE TITLE
Any Update on this project.

### ISSUE THREAD

**Issue by MathieuBujold** [AndreLGava/star-wars-font#1]

**Comment by AndreLZGava** [comment]
Hello @MathieuB27 

Do you need a specific icon?

**Comment by MathieuBujold** [comment]
I found what I was looking for her
Look at this.


Mathieu

**Comment by AndreLZGava** [comment]
Sorry, I didn't understand what you mean. Need something else?

**Comment by MathieuBujold** [comment]
Sorry my link was truncated
http://www.starwarsglyphicons.com/
